//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Album_Photo
{
    [Serializable]
    public class AlbumPhoto 
    {
        private List<Pages.GenericPage> AlbumPages { get; set; }

        public List<Pages.GenericPage> AlbumPagesProp { get { return AlbumPages; } }

        public int current_index { get; set; }

        public int albumSize { get { return AlbumPages.Count; } }

        public AlbumPhoto()
        {
            AlbumPages = new List<Pages.GenericPage>();
            current_index = -1;   
        }
       
        public Pages.GenericPage GetPageAt(int i)
        {
            if (i < 0 || i >= albumSize)
                return null;

            else 
                return AlbumPages.ElementAt(i);              
        }

        public void CreerPage(Pages.GenericPage page)
        {
            if (current_index > -1 && current_index != AlbumPages.Count-1)
            {
                current_index++;
                AlbumPages.Insert(current_index, page);
            }
            else
            {
                current_index++;
                AlbumPages.Add(page);
            }
        }

        public void DeletePage()
        {
            if (current_index > -1)
            {
                if (current_index < AlbumPages.Count-1)
                {
                    AlbumPages.RemoveAt(current_index);
                }
                else 
                {
                    //Console.WriteLine("current_index" + current_index + "    albumSize:" + albumSize);
                    AlbumPages.RemoveAt(current_index);
                    current_index--;
                }
            }
        }      

        public void ClearAll()
        {
            AlbumPages.Clear();
            current_index = -1;
        }
    }

}